import { MigrationInterface, QueryRunner } from "typeorm";

export class CompleteSchema1775749518512 implements MigrationInterface {
    name = 'CompleteSchema1775749518512'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_109638590074998bb72a2f2cf08"`);
        await queryRunner.query(`CREATE TABLE "work_orders" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "tenant_id" uuid NOT NULL, "created_by_id" uuid NOT NULL, "assigned_to_id" uuid, "machine_id" uuid, "title" character varying(255) NOT NULL, "description" text, "status" character varying NOT NULL DEFAULT 'pending', "priority" character varying NOT NULL DEFAULT 'medium', "due_date" TIMESTAMP, "completed_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_29f6c1884082ee6f535aed93660" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."sync_queue_operation_type_enum" AS ENUM('visit_check_in', 'visit_check_out', 'work_order_delivery', 'ticket_report', 'ticket_update', 'attachment_upload')`);
        await queryRunner.query(`CREATE TYPE "public"."sync_queue_status_enum" AS ENUM('PENDIENTE', 'SINCRONIZADO', 'FALLIDO', 'REVISION_MANUAL')`);
        await queryRunner.query(`CREATE TABLE "sync_queue" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "tenant_id" uuid NOT NULL, "user_id" uuid NOT NULL, "operation_type" "public"."sync_queue_operation_type_enum" NOT NULL, "status" "public"."sync_queue_status_enum" NOT NULL DEFAULT 'PENDIENTE', "payload" json NOT NULL, "retry_count" integer NOT NULL DEFAULT '0', "max_retries" integer NOT NULL DEFAULT '3', "error_message" text, "error_stack" text, "next_retry_at" TIMESTAMP, "synced_at" TIMESTAMP, "entity_id" uuid, "entity_type" character varying(50), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_ff45aae31ec336e210e9bb34e6b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sales" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "tenant_id" uuid NOT NULL, "vendor_id" uuid NOT NULL, "sector_id" uuid NOT NULL, "machine_id" uuid, "amount" numeric NOT NULL, "description" character varying, "sale_date" TIMESTAMP NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_4f0bc990ae81dba46da680895ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tickets" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "tenant_id" uuid NOT NULL, "machine_id" uuid, "created_by_id" uuid NOT NULL, "assigned_to_id" uuid, "title" character varying(255) NOT NULL, "description" text, "priority" character varying NOT NULL DEFAULT 'medium', "status" character varying NOT NULL DEFAULT 'open', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_343bc942ae261cf7a1377f48fd0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "mermas" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "tenant_id" uuid NOT NULL, "reported_by_id" uuid NOT NULL, "ticket_id" uuid, "machine_id" uuid, "product_name" character varying NOT NULL, "quantity" numeric NOT NULL, "unit_cost" numeric NOT NULL, "total_cost" numeric NOT NULL, "cause" text, "merma_date" TIMESTAMP NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_8a3ad2e0e883aa70262826c2132" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."kpis_type_enum" AS ENUM('visitas', 'ventas', 'tickets', 'mermas')`);
        await queryRunner.query(`CREATE TABLE "kpis" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "tenant_id" uuid NOT NULL, "user_id" uuid, "sector_id" uuid, "type" "public"."kpis_type_enum" NOT NULL, "name" character varying NOT NULL, "target_value" numeric NOT NULL, "current_value" numeric NOT NULL DEFAULT '0', "start_date" TIMESTAMP, "end_date" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_96cc541107cdc102a50e2b0ac90" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "password_resets" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "user_id" uuid NOT NULL, "token_prefix" character varying(8) NOT NULL, "reset_token_hash" character varying NOT NULL, "expires_at" TIMESTAMP NOT NULL, "used" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4816377aa98211c1de34469e742" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_edaba80d77d808a2e7f20482bc" ON "password_resets" ("token_prefix") `);
        await queryRunner.query(`CREATE TYPE "public"."inventory_status_enum" AS ENUM('disponible', 'en_uso', 'agotado', 'en_pedido')`);
        await queryRunner.query(`CREATE TABLE "inventory" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "tenant_id" uuid NOT NULL, "part_name" character varying NOT NULL, "part_number" character varying, "description" character varying, "quantity" integer NOT NULL DEFAULT '0', "min_quantity" integer NOT NULL DEFAULT '0', "unit_cost" numeric, "status" "public"."inventory_status_enum" NOT NULL DEFAULT 'disponible', "location" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_82aa5da437c5bbfb80703b08309" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "attachments" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "tenant_id" uuid NOT NULL, "uploaded_by_id" uuid NOT NULL, "entity_type" character varying(50) NOT NULL, "entity_id" uuid NOT NULL, "url" character varying NOT NULL, "file_name" character varying(255) NOT NULL, "mime_type" character varying(100) NOT NULL, "file_size" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_5e1f050bcff31e3084a1d662412" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "tenant_name"`);
        await queryRunner.query(`ALTER TABLE "tenants" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "tenants" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "tenant_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_7a822393037d08be61bed48944b"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "rut"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "rut" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_7a822393037d08be61bed48944b" UNIQUE ("rut")`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password_hash"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password_hash" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "first_name"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "first_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "last_name"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "last_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "phone" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "machines" DROP CONSTRAINT "UQ_c7c3a3353238c4e71535a30ddd3"`);
        await queryRunner.query(`ALTER TABLE "machines" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "machines" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sectors" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sectors" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" ADD CONSTRAINT "UQ_eb8559946673fe848e1a2d42602" UNIQUE ("machine_id")`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" DROP CONSTRAINT "UQ_72793306a91bcbf1e8d1cfec00b"`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" DROP COLUMN "uid"`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" ADD "uid" character varying(14) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" ADD CONSTRAINT "UQ_72793306a91bcbf1e8d1cfec00b" UNIQUE ("uid")`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" DROP COLUMN "tag_model"`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" ADD "tag_model" character varying(20) NOT NULL DEFAULT 'NTAG-215'`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" DROP COLUMN "hardware_model"`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" ADD "hardware_model" character varying(20) NOT NULL DEFAULT 'NTAG215'`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" DROP COLUMN "machine_serial_id"`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" ADD "machine_serial_id" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" DROP COLUMN "tenant_id_obfuscated"`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" ADD "tenant_id_obfuscated" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" DROP COLUMN "integrity_checksum"`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" ADD "integrity_checksum" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "visits" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "visits" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "machines" ADD CONSTRAINT "FK_8966ebe117dc2bc64dd95af9cda" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_orders" ADD CONSTRAINT "FK_0059be3d968bef25dcf779f043e" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_orders" ADD CONSTRAINT "FK_892244c7e30eda7d2406dda545b" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_orders" ADD CONSTRAINT "FK_791ae6a4a4f03205d47270e0c62" FOREIGN KEY ("assigned_to_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_orders" ADD CONSTRAINT "FK_cb53584b8b20af62e8a78ce8a6f" FOREIGN KEY ("machine_id") REFERENCES "machines"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sync_queue" ADD CONSTRAINT "FK_d6c187cbf5d2268060086127829" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sync_queue" ADD CONSTRAINT "FK_1605c43d06cf9c9c3059eaa4e62" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sectors" ADD CONSTRAINT "FK_52fe440885ad9818f5d9d0a3931" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_ae6cc7812b56c7a03599a407d90" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_931b8c73a5943d6559244eda062" FOREIGN KEY ("vendor_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_e33bdf0f4f0e44cad2fa20fcf28" FOREIGN KEY ("sector_id") REFERENCES "sectors"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_a6178d9c57ee72354e3ac965e76" FOREIGN KEY ("machine_id") REFERENCES "machines"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" ADD CONSTRAINT "FK_eb8559946673fe848e1a2d42602" FOREIGN KEY ("machine_id") REFERENCES "machines"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" ADD CONSTRAINT "FK_b59ebeb74c39385a22914bac017" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_d4beb915a8f7487afcb2d073c01" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_9ad7b44d2ebc86a477684e98f11" FOREIGN KEY ("machine_id") REFERENCES "machines"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_f131b2269095005a89841a11e4a" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_b564a18159530b5a56aeac33d1a" FOREIGN KEY ("assigned_to_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "visits" ADD CONSTRAINT "FK_8575b345fcc2bc2fc2161295cba" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "visits" ADD CONSTRAINT "FK_e9c1e480fe2f2275fb54cdc01cd" FOREIGN KEY ("technician_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "visits" ADD CONSTRAINT "FK_c2e6755ee65c580615296677e16" FOREIGN KEY ("machine_id") REFERENCES "machines"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mermas" ADD CONSTRAINT "FK_533f4dbc56451c309426188936e" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mermas" ADD CONSTRAINT "FK_34bbf2ed9ce87ad40a60969be3d" FOREIGN KEY ("reported_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mermas" ADD CONSTRAINT "FK_99c432323a1dacb8ab2ff862cd2" FOREIGN KEY ("ticket_id") REFERENCES "tickets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mermas" ADD CONSTRAINT "FK_75597ce2fad04da4452f46ec02f" FOREIGN KEY ("machine_id") REFERENCES "machines"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kpis" ADD CONSTRAINT "FK_480d834b279982a9714e6b53028" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kpis" ADD CONSTRAINT "FK_75cd42b51d618b98db59e084330" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kpis" ADD CONSTRAINT "FK_91a2e65019828fd173473ceaf7f" FOREIGN KEY ("sector_id") REFERENCES "sectors"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "password_resets" ADD CONSTRAINT "FK_f7a4c3bc48f24df007936d217be" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory" ADD CONSTRAINT "FK_b629298a32fb8df03cb5f35af67" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attachments" ADD CONSTRAINT "FK_7058f2082c7a4ddc189ad7c9a86" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attachments" ADD CONSTRAINT "FK_70a38fc450d3b433c86b67e69d6" FOREIGN KEY ("uploaded_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "attachments" DROP CONSTRAINT "FK_70a38fc450d3b433c86b67e69d6"`);
        await queryRunner.query(`ALTER TABLE "attachments" DROP CONSTRAINT "FK_7058f2082c7a4ddc189ad7c9a86"`);
        await queryRunner.query(`ALTER TABLE "inventory" DROP CONSTRAINT "FK_b629298a32fb8df03cb5f35af67"`);
        await queryRunner.query(`ALTER TABLE "password_resets" DROP CONSTRAINT "FK_f7a4c3bc48f24df007936d217be"`);
        await queryRunner.query(`ALTER TABLE "kpis" DROP CONSTRAINT "FK_91a2e65019828fd173473ceaf7f"`);
        await queryRunner.query(`ALTER TABLE "kpis" DROP CONSTRAINT "FK_75cd42b51d618b98db59e084330"`);
        await queryRunner.query(`ALTER TABLE "kpis" DROP CONSTRAINT "FK_480d834b279982a9714e6b53028"`);
        await queryRunner.query(`ALTER TABLE "mermas" DROP CONSTRAINT "FK_75597ce2fad04da4452f46ec02f"`);
        await queryRunner.query(`ALTER TABLE "mermas" DROP CONSTRAINT "FK_99c432323a1dacb8ab2ff862cd2"`);
        await queryRunner.query(`ALTER TABLE "mermas" DROP CONSTRAINT "FK_34bbf2ed9ce87ad40a60969be3d"`);
        await queryRunner.query(`ALTER TABLE "mermas" DROP CONSTRAINT "FK_533f4dbc56451c309426188936e"`);
        await queryRunner.query(`ALTER TABLE "visits" DROP CONSTRAINT "FK_c2e6755ee65c580615296677e16"`);
        await queryRunner.query(`ALTER TABLE "visits" DROP CONSTRAINT "FK_e9c1e480fe2f2275fb54cdc01cd"`);
        await queryRunner.query(`ALTER TABLE "visits" DROP CONSTRAINT "FK_8575b345fcc2bc2fc2161295cba"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_b564a18159530b5a56aeac33d1a"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_f131b2269095005a89841a11e4a"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_9ad7b44d2ebc86a477684e98f11"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_d4beb915a8f7487afcb2d073c01"`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" DROP CONSTRAINT "FK_b59ebeb74c39385a22914bac017"`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" DROP CONSTRAINT "FK_eb8559946673fe848e1a2d42602"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_a6178d9c57ee72354e3ac965e76"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_e33bdf0f4f0e44cad2fa20fcf28"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_931b8c73a5943d6559244eda062"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_ae6cc7812b56c7a03599a407d90"`);
        await queryRunner.query(`ALTER TABLE "sectors" DROP CONSTRAINT "FK_52fe440885ad9818f5d9d0a3931"`);
        await queryRunner.query(`ALTER TABLE "sync_queue" DROP CONSTRAINT "FK_1605c43d06cf9c9c3059eaa4e62"`);
        await queryRunner.query(`ALTER TABLE "sync_queue" DROP CONSTRAINT "FK_d6c187cbf5d2268060086127829"`);
        await queryRunner.query(`ALTER TABLE "work_orders" DROP CONSTRAINT "FK_cb53584b8b20af62e8a78ce8a6f"`);
        await queryRunner.query(`ALTER TABLE "work_orders" DROP CONSTRAINT "FK_791ae6a4a4f03205d47270e0c62"`);
        await queryRunner.query(`ALTER TABLE "work_orders" DROP CONSTRAINT "FK_892244c7e30eda7d2406dda545b"`);
        await queryRunner.query(`ALTER TABLE "work_orders" DROP CONSTRAINT "FK_0059be3d968bef25dcf779f043e"`);
        await queryRunner.query(`ALTER TABLE "machines" DROP CONSTRAINT "FK_8966ebe117dc2bc64dd95af9cda"`);
        await queryRunner.query(`ALTER TABLE "visits" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "visits" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" DROP COLUMN "integrity_checksum"`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" ADD "integrity_checksum" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" DROP COLUMN "tenant_id_obfuscated"`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" ADD "tenant_id_obfuscated" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" DROP COLUMN "machine_serial_id"`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" ADD "machine_serial_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" DROP COLUMN "hardware_model"`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" ADD "hardware_model" character varying NOT NULL DEFAULT 'NTAG215'`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" DROP COLUMN "tag_model"`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" ADD "tag_model" character varying NOT NULL DEFAULT 'NTAG-215'`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" DROP CONSTRAINT "UQ_72793306a91bcbf1e8d1cfec00b"`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" DROP COLUMN "uid"`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" ADD "uid" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" ADD CONSTRAINT "UQ_72793306a91bcbf1e8d1cfec00b" UNIQUE ("uid")`);
        await queryRunner.query(`ALTER TABLE "nfc_tags" DROP CONSTRAINT "UQ_eb8559946673fe848e1a2d42602"`);
        await queryRunner.query(`ALTER TABLE "sectors" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "sectors" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "machines" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "machines" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "machines" ADD CONSTRAINT "UQ_c7c3a3353238c4e71535a30ddd3" UNIQUE ("serial_number")`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "phone" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "last_name"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "last_name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "first_name"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "first_name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password_hash"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password_hash" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_7a822393037d08be61bed48944b"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "rut"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "rut" character varying(12)`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_7a822393037d08be61bed48944b" UNIQUE ("rut")`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "tenant_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tenants" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "tenants" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ADD "tenant_name" character varying(255)`);
        await queryRunner.query(`DROP TABLE "attachments"`);
        await queryRunner.query(`DROP TABLE "inventory"`);
        await queryRunner.query(`DROP TYPE "public"."inventory_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_edaba80d77d808a2e7f20482bc"`);
        await queryRunner.query(`DROP TABLE "password_resets"`);
        await queryRunner.query(`DROP TABLE "kpis"`);
        await queryRunner.query(`DROP TYPE "public"."kpis_type_enum"`);
        await queryRunner.query(`DROP TABLE "mermas"`);
        await queryRunner.query(`DROP TABLE "tickets"`);
        await queryRunner.query(`DROP TABLE "sales"`);
        await queryRunner.query(`DROP TABLE "sync_queue"`);
        await queryRunner.query(`DROP TYPE "public"."sync_queue_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."sync_queue_operation_type_enum"`);
        await queryRunner.query(`DROP TABLE "work_orders"`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_109638590074998bb72a2f2cf08" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
